### ISSUE TITLE
Not working with docker jupyter/minimal-notebook

### ISSUE THREAD

**Issue by youenchene** [saagie/jupyter-saagie-plugin#1]
Got this screen after clicking on the Saagie icon :

![image](https://cloud.githubusercontent.com/assets/1607244/23092385/08ee5b1e-f5ca-11e6-8e0c-2640a02dd20e.png)

FROM jupyter/minimal-notebook

MAINTAINER Saagie

RUN pip install --upgrade pip

#Install Saagie Plugin

RUN pip install https://github.com/saagie/jupyter-saagie-plugin/archive/0.4.0.tar.gz

# Run the notebook

CMD jupyter notebook \

    --ip=* \

    --MappingKernelManager.time_to_dead=10 \

    --MappingKernelManager.first_beat=3 \

#    --notebook-dir=/notebooks-dir/

**Comment by BertrandBordage** [comment]
This is due to the recent changes in [Saagie’s configuration view](https://manager.prod.saagie.io/api-internal/v1/platform).
Previously, it was returning an HTTP status code 403 (if I remember well). Since a few days, it now redirects to the login page. So the HTTP status code unexpectedly became 200 because requests follows redirections by default.

This issue is fixed by 4bc72e81925d0cc5a204ffe8f2277b3f40268850, available in 0.4.1.
